### ISSUE TITLE
아주아주오랜만인 이슈네요.

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/whatIThink#28]
안녕하세요.
한달이 넘는 시간만에 이슈를 쓰는 것 같아요.
공부는 조금씩했는데 글을 쓰거나 그러지 못했네요.

1. 발표준비
발표준비는 지금 한창!! 하는 중이예요.
대략적인 스토리흐름은 잡았고 PPT만들면서 내용 보강할 예정입니다.
내일까지는 완성 못하겠지만 그래도 보여드리고 이야기나누면 좋을 것 같아요.

2. 요새는 Three.js에 관해서 좀 찾아보고 있어요.
업무적으로 Web AR관련해서 찾아본거지만 나름 요새 기술(?)인 것 같고 더 찾아보다가
관련된 것으로 개인적인 작은 플젝으로 만들어도 결과물이 풍부해질 수 있겠다하는 마음이 들어서요.

3. 개인 공부시간
회사에 엄청난 분이 퇴사하시면서 그 여파로 야근도 하게 되고 밤샘도 하루 해봤네요.
더불어 연말모임까지 노는 시간도 많아 근 한달은 개인 공부시간이 없었어요.

스스로 개발자라는 이름의 무게를 느끼는 편인데.. 그래서 요새 반성하는 생각이 많이 들어요.
다시 폭풍같은 스케쥴에서 벗어나 순간의 피곤함을 이기고 책상에 앉는 시간을 늘리려고 노력중입니다. 
다시 제자리를 잘 찾아보겠습니다.
늘 반성만 하는 것 같지만 또 그것을 자책하는 시간을 가지는 것 보다
다음 멘토링까지 공부하면서 함께 이야기할 내용을 만드는 것으로 보여드릴게요!

4. 회사
저번 멘토링 시간에도 이에 관한 많은 이야기를 나누고 어느 정도 조언도 해주셨지만
2달정도 지난 현 상황에 대해서 말씀드리고 마무리 지을 수 있을 것 같습니다.

감사합니다.

**Comment by jongfeel** [comment]
좋은 리뷰의 시간이었습니다.

미팅 파일은 아래 pull request 내용으로 확인해 주세요.
#29
