### ISSUE TITLE
굿즈관련 이슈입니다

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/whatIThink#30]
아까 말씀드렸던 굿즈 예시입니다 ㅎㅎ
![Screenshot_20191207-200204_Facebook](https://user-images.githubusercontent.com/41983574/70375098-40422e80-193d-11ea-8131-165c6fca4fd7.jpg)

@jongfeel

**Comment by jongfeel** [comment]
@WonjeongPark 

아주 좋은 아이디어입니다.

이걸
https://github.com/jongfeel/HomeComingDay2019/issues

요기에 올려주시면 더 좋을 거 같아요!
