### ISSUE TITLE
WebAR관련

### ISSUE THREAD

**Issue by wonjeongpark-THEHRDer** [WonjeongPark/whatIThink#31]
안녕하세요.
계속 WebAR관련해서 찾아보고 있는 중인데요,
marker없이 WebAR을 구동시켜  증강된 3D 오브젝트와 같이 사진을 찍을 수 있게? 하고 싶은데 
위치기반으로 하는 것은 여러 사용자들에게 적용이 안될 것 같고,
AR.js는 markerless를 지원하지 않는 것(?) 같고
https://github.com/jeromeetienne/AR.js#what-marker-based-means
현재 구글에서 beta버전처럼 나온 것이 있는 것 같은데
https://developers.google.com/web/updates/2018/06/ar-for-the-web 
제 컴퓨터나 모바일에서는 실행이 안되서
다른 방법을 모색중입니다. 혹시 작은 힌트 있으시면 알려주세요.
'그건 아직 안됩니다!' 라던지 이런 말도 감사합니다.

분명 자바스크립트로 씌여진 코드들인데 다른 언어 코드 읽는 것 보다 더 어려운 것 같아요.
관련 자료 읽는 것 보다 하나라도 증강시켜 화면에 올려보자하는데 막상 그러려고하면
아무것도 모르는 것 같은 느낌도 들고요 ㅜㅜ 다시 1년 전으로 돌아간 느낌이 들었어요.

+ howto에 passport.js적용하는 것도 틈틈히 하는 중입니다.
오랜만이라 다시 이것저것 찾아보느라 시간이 걸리네요.
왜 안되는 건지 차근차근 찾아보는 중이라 곧 해결될 것 같아요!

@jongfeel

**Comment by jongfeel** [comment]
@wonjeongpark-THEHRDer 

우선 Web에서 AR 하는 것 중에 원정님이 하고 싶어하는 건 아래 키워드로 검색하신 다음에 찾아보면 됩니다.

WebXR

그리고 marker 없이 AR을 하는 건 기본적으로 공간상에 뭘 띄우는 것 부터 시작하는데요
그건 아래 키워드 들로 찾아 보시면 될거에요.

Spatial tracking
Spatial mapping - hololens
Motion tracking - ARCore
World tracking - ARKit

아직 web에서는 spatial tracking은 없어 보입니다.
그런데 혹시 몰라요 어디선가 누군가 구현한게 있고 못찾았을 수도 있죠.

그리고 구글의 예제는 아마 ARCore를 사용해야 하고
ARCore를 쓰려면 카메라와 센서가 달린 모바일 디바이스를 사용해야 합니다.

자바스크립트가 어느 동네에서 쓰이느냐에 따라서 느낌이 다른 걸 경험하신거면
또 좋은 경험일 수 있어요.

다른 언어도 다른 플랫폼에서의 코드 모양새가 조금씩 다르거든요.
예로 안드로이드에서 코딩하는 Java와 웹 스프링 프레임워크에서 쓰는 Java는 조금 그리고 많이 다릅니다.

**Comment by WonjeongPark** [comment]
감사합니다.
알려주신 것 토대로 더 찾아보고 어떤 것을 알게되었나 글로 써볼게요!
멘토님 발표하실때는 설명 중에서 많이 알아들어서 나름 열심히 공부했다고 생각했는데
그게아니라 멘토님이 알기쉽게 잘 설명해주신거라는 걸 다시 느끼고 있습니다.
제가 자꾸 태블릿을 회사에 두고 다녀서 동영상 보내드리는 것이 늦네요!
죄송해요! 멘토링 전에 보내드리겠습니다!

**Comment by jongfeel** [comment]
준비 잘 한 다음에 저랑 리뷰하면 언제나 그랬듯이 많은 도움이 되실 거에요.
영상은 천천히 준비되면 주세요 ㅎㅎ

**Comment by WonjeongPark** [comment]
40분이 넘는 영상이라 그런지 용량이 크긴 크네요. 알려주신 방법으로 시도해보겠습니다!

그리고 어제 정해진 사항인데,
회사 일때문에 이번주는 크리스마스도 못쉬고 출근할 것 같아요. 이번주까지 해야하는 일이라 아마 목,금은 야근할 것 같아서요. 갑자기
Three.js를 활용해야하는데 처음 해보는 거라 아직 좀 어려워서 시간이 더 걸릴 것 같네요.. 대신 다음주 주중에 이틀을
쉬기로했어요! 멘토링을 2일에 진행해도 될까요? 스케쥴 확인하셔서 답 주세요.

늘 감사합니다.



2019년 12월 24일 (화) 오전 11:53, Kim Jong Feel <notifications@github.com>님이 작성:

**Comment by wonjeongpark-THEHRDer** [comment]
일정조정에 관해서 메일로 답장드린건데, 이슈 댓글 알림메일에 바로 답장한거라 그런지 댓글로도 써졌네요! 댓글로 말씀드릴 내용은 아니라서 삭제했습니다!
