### ISSUE TITLE
이슈가 늦었네요.

### ISSUE THREAD

**Issue by wonjeongpark-THEHRDer** [WonjeongPark/whatIThink#35]
안녕하세요. 박원정입니다.
오랜만에 멘토링인데 이슈가 늦었네요.
우선 howto는 마무리인걸로 해야할 것 같아요.
아직 passport.js 적용이 완전 끝나지 않았는데
우선 프로젝트는 마무리하고 나중에라도 적용은 끝낼 생각입니다. 

새 프로젝트는 React Native로 하이브리드 앱을 만들어 보고 싶어서 방향을 잡았습니다.
1. React Native 관련 간단한 정리글 쓰는 중이고 주제는 아직 못정했어요.
해보고싶은게 많아서 욕심만 많네요. 각각의 주제마다 하고싶은 기능들은 대략적으로 정해져있어서
2. 멘토링 전에 주제를 정하고 하고 싶은 기능들 정리하는 것이 목표입니다.

감사합니다.
@jongfeel

**Comment by jongfeel** [comment]
@wonjeongpark-THEHRDer 

이것 저것 또 많은 걸 정리해 보신 듯 하네요.
React Native 보다는 만드려고 하는 주제를 잘 정하는 것이 중요합니다.

리뷰를 해 보면서 뭘 하면 좋을지 얘기해 보는 게 좋을 것 같습니다.
